name: Fintech DB Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.actor == 'Abdelrahman-AA'
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Root Dependencies
        run: npm install

      - name: Project Setup (Clean & Install)
        run: npm run setup:run

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./db-testing-framework

      - name: Execute Full Automation Suite
        run: npm run test:full

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: db-testing-framework/playwright-report/

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4